name: organoid_tracker
channels:
  - conda-forge
  - ilastik-forge
dependencies:
  - _libavif_api=1.3.0=h57928b3_2
  - _openmp_mutex=4.5=2_gnu
  - absl-py=2.3.1=pyhd8ed1ab_0
  - aicspylibczi=3.3.1=py311h3e6a449_2
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.3=py311ha56572f_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - aom=3.9.1=he0c23c2_0
  - attrs=25.4.0=pyhcf101f3_1
  - autograd=1.8.0=pyhd8ed1ab_0
  - autograd-gamma=0.5.0=pyhd8ed1ab_1
  - backports.zstd=1.3.0=py311h71c1bcc_0
  - blosc=1.21.6=hfd34d9b_1
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - brotli-python=1.2.0=py311hc5da9e4_1
  - bzip2=1.0.8=h0ad9c76_8
  - c-blosc2=2.22.0=h2af8807_1
  - ca-certificates=2026.1.4=h4c7d964_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h477c42c_1
  - certifi=2026.1.4=pyhd8ed1ab_0
  - charls=2.4.2=h1537add_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyha7b4d00_1
  - cloudpickle=3.1.2=pyhcf101f3_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.3=py311h3fd045d_3
  - cuda-cudart=12.9.79=he0c23c2_0
  - cuda-cudart_win-64=12.9.79=he0c23c2_0
  - cuda-cupti=12.9.79=hac47afa_1
  - cuda-nvrtc=12.9.86=hac47afa_1
  - cuda-version=12.9=h4f385c5_3
  - cycler=0.12.1=pyhcf101f3_2
  - cytoolz=1.1.0=py311h3485c13_1
  - dask-core=2026.1.2=pyhcf101f3_0
  - dav1d=1.2.1=hcfcfb64_0
  - deprecated=1.3.1=pyhd8ed1ab_0
  - distributed=2026.1.2=pyhcf101f3_0
  - donfig=0.8.1.post1=pyhd8ed1ab_1
  - double-conversion=3.4.0=hac47afa_0
  - dpct=1.3.0.1.post11=py311h926c15e_0
  - filelock=3.20.1=pyhd8ed1ab_0
  - fmt=12.1.0=h7f4e812_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py311h3f79411_0
  - formulaic=1.2.1=pyhd8ed1ab_2
  - freetype=2.14.1=h57928b3_0
  - frozenlist=1.7.0=py311hdf60d3a_0
  - fsspec=2025.12.0=pyhd8ed1ab_0
  - geff=1.1.4.1.1=pyhcf101f3_0
  - geff-spec=1.1.1=pyhcf101f3_0
  - giflib=5.2.2=h64bf75a_0
  - glpk=5.0=h8ffe710_0
  - google-crc32c=1.8.0=py311h178015e_0
  - graphite2=1.3.14=hac47afa_2
  - h2=4.3.0=pyhcf101f3_0
  - h5py=3.15.1=nompi_py311hc40ba4b_101
  - harfbuzz=12.3.2=h5a1b470_0
  - hdf5=1.14.6=nompi_h89f0904_104
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.2=h637d24d_0
  - idna=3.11=pyhd8ed1ab_0
  - imagecodecs=2025.11.11=py311h956b223_1
  - imageio=2.37.0=pyhfb79c49_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - interface_meta=1.3.0=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - jxrlib=1.1=hcfcfb64_3
  - keras=3.12.0=pyh753f3f9_0
  - kiwisolver=1.4.9=py311h275cad7_2
  - krb5=1.21.3=hdf4eb48_0
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=hbcf6048_0
  - lemon=1.3.1=h8fac5c6_11
  - lerc=4.0.0=h6470a55_1
  - libabseil=20260107.0=cxx17_h0eb2380_0
  - libaec=1.1.4=h20038f6_0
  - libavif16=1.3.0=he916da2_2
  - libblas=3.11.0=5_hf2e6a31_mkl
  - libboost=1.86.0=h9dfe17d_4
  - libboost-python=1.86.0=py311h05ac4f6_4
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.11.0=5_h2a3cdd5_mkl
  - libclang13=21.1.8=default_ha2db4b5_3
  - libcrc32c=1.1.2=h0e60522_0
  - libcublas=12.9.1.4=hac47afa_1
  - libcudnn=9.10.2.21=hca898b4_0
  - libcudss=0.7.1.4=hca898b4_0
  - libcufft=11.4.1.4=hac47afa_1
  - libcurand=10.3.10.19=hac47afa_1
  - libcurl=8.17.0=h43ecb02_1
  - libcusolver=11.7.5.82=hac47afa_2
  - libcusparse=12.5.10.65=hac47afa_2
  - libdeflate=1.25=h51727cc_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_16
  - libglib=2.86.3=h0c9aed9_0
  - libgomp=15.2.0=h8ee18e1_16
  - libhwloc=2.12.1=default_h4379cf1_1003
  - libhwy=1.3.0=ha71e874_1
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - libjxl=0.11.1=hac9b6f3_5
  - liblapack=3.11.0=5_hf9ab0e9_mkl
  - liblzma=5.8.2=hfd05255_0
  - libmagma=2.9.0=hb6a17ea_3
  - libnvjitlink=12.9.86=hac47afa_2
  - libpng=1.6.54=h7351971_0
  - libprotobuf=6.33.5=h61fc761_0
  - libsqlite=3.51.2=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libtiff=4.7.1=h8f73337_1
  - libtorch=2.10.0=cuda128_mkl_h961e73d_302
  - libuv=1.51.0=hfd05255_1
  - libvulkan-loader=1.4.341.0=h477610d_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.15.1=h779ef1b_1
  - libxml2-16=2.15.1=h3cfd58e_1
  - libxslt=1.1.43=h0fbe4c1_1
  - libzlib=1.3.1=h2466b09_2
  - libzopfli=1.0.3=h0e60522_0
  - lifelines=0.30.1=pyhd8ed1ab_0
  - llvm-openmp=21.1.8=h4fa8253_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4-c=1.10.0=h2466b09_1
  - markdown=3.10.1=pyhcf101f3_0
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py311h3f79411_0
  - matplotlib-base=3.10.8=py311h1675fdf_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mkl=2025.3.0=hac47afa_454
  - ml_dtypes=0.5.4=np2py311hf2e69b3_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msgpack-python=1.1.2=py311h3fd045d_1
  - multidict=6.7.0=py311h3f79411_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - namex=0.1.0=pyhd8ed1ab_0
  - narwhals=2.14.0=pyhcf101f3_0
  - nd2reader=3.3.1=pyhd8ed1ab_0
  - networkx=3.6.1=pyhcf101f3_0
  - numcodecs=0.16.5=py311h11fd7f3_0
  - numpy=2.3.5=py311h80b3fa1_0
  - ome-zarr=0.12.2=pyhd8ed1ab_1
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.6.1=hf411b9b_1
  - optree=0.18.0=py311h3fd045d_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311h11fd7f3_2
  - partd=1.4.2=pyhd8ed1ab_0
  - pcre2=10.47=hd2b5f0e_0
  - pillow=12.0.0=py311h17b8079_2
  - pims=0.7=pyhd8ed1ab_1
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h5112557_1
  - propcache=0.3.1=py311h5082efb_0
  - psutil=7.2.2=py311hf893f09_0
  - pthread-stubs=0.4=h0e40799_1002
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-abi=11=hc364b38_1
  - pybind11-global=3.0.1=pyh5e4992e_0
  - pydantic=2.12.5=pyhcf101f3_1
  - pydantic-core=2.41.5=py311hf51aa87_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyside6=6.10.2=py311hf70c7b4_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.11.14=h0159041_3_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.11=8_cp311
  - pytorch=2.10.0=cuda128_mkl_py311_ha828eda_302
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py311h3f79411_0
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.10.2=h68b6638_4
  - rav1e=0.7.1=ha073cba_3
  - requests=2.32.5=pyhcf101f3_1
  - rich=14.2.0=pyhcf101f3_0
  - scikit-image=0.25.2=py311h11fd7f3_2
  - scikit-learn=1.8.0=np2py311hd01f973_1
  - scipy=1.16.3=py311hf127856_1
  - setuptools=80.9.0=pyhff2d567_0
  - shellingham=1.5.4=pyhd8ed1ab_2
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=h67fd636_0
  - slicerator=1.1.0=pyhd8ed1ab_1
  - snappy=1.2.2=h7fa0ca8_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - svt-av1=3.1.2=hac47afa_0
  - sympy=1.14.0=pyh04b8f61_5
  - tbb=2022.3.0=hd094cb3_1
  - tblib=3.2.2=pyhcf101f3_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tifffile=2026.1.28=pyhd8ed1ab_0
  - tk=8.6.13=h2c6b04d_3
  - toolz=1.1.0=pyhd8ed1ab_1
  - tornado=6.5.4=py311h3485c13_0
  - tqdm=4.67.3=pyha7b4d00_0
  - typer=0.20.0=pyhefaf540_1
  - typer-slim=0.20.0=pyhcf101f3_1
  - typer-slim-standard=0.20.0=h4daf872_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=h8577fbf_0
  - ucrt=10.0.26100.0=h57928b3_0
  - unicodedata2=17.0.0=py311h3485c13_1
  - urllib3=2.6.3=pyhd8ed1ab_0
  - vc=14.3=h2b53caa_33
  - vc14_runtime=14.44.35208=h818238b_33
  - vcomp14=14.44.35208=h818238b_33
  - vs2015_runtime=14.44.35208=h38c0c73_33
  - wheel=0.45.1=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - wrapt=1.17.3=py311h3485c13_1
  - xmltodict=1.0.2=pyhcf101f3_0
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - yaml=0.2.5=h6a83c73_3
  - yarl=1.22.0=py311h3f79411_0
  - zarr=3.1.5=pyhcf101f3_0
  - zfp=1.0.1=h2f0f97f_3
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhcf101f3_1
  - zlib-ng=2.3.2=h0261ad2_1
  - zstd=1.5.7=h534d264_6
prefix: E:\Programs\miniforge3\envs\organoid_tracker
