name: organoid_tracker
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ilastik-forge::dpct
  - matplotlib-base
  - tifffile
  - scikit-image
  - scikit-learn
  - scipy
  - nd2reader
  - pyside6
  - pandas
  - h5py
  - lifelines
  - markdown
  - keras
  - pytorch
  - aicspylibczi
