name: organoid_tracker
channels:
  - conda-forge
  - ilastik-forge
dependencies:
  - _libavif_api=1.3.0=h57928b3_2
  - _openmp_mutex=4.5=2_gnu
  - absl-py=2.3.1=pyhd8ed1ab_0
  - aicspylibczi=3.3.1=py311h3e6a449_2
  - aom=3.9.1=he0c23c2_0
  - autograd=1.8.0=pyhd8ed1ab_0
  - autograd-gamma=0.5.0=pyhd8ed1ab_1
  - blosc=1.21.6=hfd34d9b_1
  - brotli=1.2.0=h17ff524_0
  - brotli-bin=1.2.0=h6910e44_0
  - bzip2=1.0.8=h0ad9c76_8
  - c-blosc2=2.22.0=h3cf07e4_0
  - ca-certificates=2025.11.12=h4c7d964_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h5782bbf_0
  - charls=2.4.2=h1537add_0
  - contourpy=1.3.3=py311h3fd045d_2
  - crc32c=2.8=py311hf893f09_0
  - cuda-cudart=12.9.79=he0c23c2_0
  - cuda-cudart_win-64=12.9.79=he0c23c2_0
  - cuda-cupti=12.9.79=hac47afa_1
  - cuda-nvrtc=12.9.86=hac47afa_1
  - cuda-version=12.9=h4f385c5_3
  - cudnn=9.10.1.4=h32ff316_1
  - cycler=0.12.1=pyhd8ed1ab_1
  - dav1d=1.2.1=hcfcfb64_0
  - deprecated=1.3.1=pyhd8ed1ab_0
  - donfig=0.8.1.post1=pyhd8ed1ab_1
  - double-conversion=3.3.1=he0c23c2_0
  - dpct=1.3.0.1.post11=py311h926c15e_0
  - filelock=3.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.60.1=py311h3f79411_0
  - formulaic=1.2.1=pyhd8ed1ab_2
  - freetype=2.14.1=h57928b3_0
  - fsspec=2025.10.0=pyhd8ed1ab_0
  - giflib=5.2.2=h64bf75a_0
  - glpk=5.0=h8ffe710_0
  - graphite2=1.3.14=hac47afa_2
  - h5py=3.15.1=nompi_py311hc40ba4b_100
  - harfbuzz=12.1.0=h5f2951f_0
  - hdf5=1.14.6=nompi_he30205f_103
  - icu=75.1=he0c23c2_0
  - imagecodecs=2025.8.2=py311haf4ede9_7
  - imageio=2.37.0=pyhfb79c49_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - interface_meta=1.3.0=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - jxrlib=1.1=hcfcfb64_3
  - keras=3.12.0=pyh753f3f9_0
  - kiwisolver=1.4.9=py311h275cad7_1
  - krb5=1.21.3=hdf4eb48_0
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=hbcf6048_0
  - lemon=1.3.1=h8fac5c6_11
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250512.1=cxx17_habfad5f_0
  - libaec=1.1.4=h20038f6_0
  - libavif16=1.3.0=he916da2_2
  - libblas=3.9.0=38_hf2e6a31_mkl
  - libboost=1.86.0=h9dfe17d_4
  - libboost-python=1.86.0=py311h05ac4f6_4
  - libbrotlicommon=1.2.0=hc82b238_0
  - libbrotlidec=1.2.0=h431afc6_0
  - libbrotlienc=1.2.0=ha521d6b_0
  - libcblas=3.9.0=38_h2a3cdd5_mkl
  - libclang13=21.1.5=default_ha2db4b5_0
  - libcublas=12.9.1.4=hac47afa_1
  - libcudnn=9.10.1.4=hca898b4_1
  - libcudnn-dev=9.10.1.4=hca898b4_1
  - libcudss=0.7.1.4=hca898b4_0
  - libcufft=11.4.1.4=hac47afa_1
  - libcurand=10.3.10.19=hac47afa_1
  - libcurl=8.17.0=h43ecb02_0
  - libcusolver=11.7.5.82=hac47afa_2
  - libcusparse=12.5.10.65=hac47afa_2
  - libdeflate=1.25=h51727cc_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h1383e82_7
  - libglib=2.86.1=hd9c3897_1
  - libgomp=15.2.0=h1383e82_7
  - libhwloc=2.12.1=default_h64bd3f2_1002
  - libhwy=1.3.0=ha71e874_1
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - libjxl=0.11.1=hac9b6f3_5
  - liblapack=3.9.0=38_hf9ab0e9_mkl
  - liblzma=5.8.1=h2466b09_2
  - libmagma=2.9.0=hb6a17ea_3
  - libnvjitlink=12.9.86=hac47afa_2
  - libpng=1.6.50=h7351971_1
  - libprotobuf=6.31.1=hdcda5b4_2
  - libsqlite=3.51.0=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libtiff=4.7.1=h8f73337_1
  - libtorch=2.8.0=cuda128_mkl_hb35488f_302
  - libuv=1.51.0=hfd05255_1
  - libvulkan-loader=1.4.328.1=h477610d_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.15.1=ha29bfb0_0
  - libxml2-16=2.15.1=h06f855e_0
  - libxslt=1.1.43=h0fbe4c1_1
  - libzlib=1.3.1=h2466b09_2
  - libzopfli=1.0.3=h0e60522_0
  - lifelines=0.30.0=pyhd8ed1ab_1
  - llvm-openmp=21.1.5=hfa2b4ca_0
  - lz4-c=1.10.0=h2466b09_1
  - markdown=3.10=pyhd8ed1ab_0
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py311h3f79411_0
  - matplotlib-base=3.10.7=py311h1675fdf_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mkl=2025.3.0=hac47afa_454
  - ml_dtypes=0.5.1=py311h11fd7f3_1
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msgpack-python=1.1.2=py311h3fd045d_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - namex=0.1.0=pyhd8ed1ab_0
  - narwhals=2.10.2=pyhcf101f3_0
  - nd2reader=3.3.1=pyhd8ed1ab_0
  - networkx=3.5=pyhe01879c_0
  - numcodecs=0.16.1=py311h11fd7f3_2
  - numpy=2.3.4=py311h80b3fa1_0
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.6.0=h725018a_0
  - optree=0.17.0=py311h3fd045d_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311h11fd7f3_1
  - pcre2=10.46=h3402e2f_0
  - pillow=12.0.0=py311hf7ee305_0
  - pims=0.7=pyhd8ed1ab_1
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h5112557_1
  - pthread-stubs=0.4=h0e40799_1002
  - pybind11=2.13.6=pyhc790b64_3
  - pybind11-abi=4=hd8ed1ab_3
  - pybind11-global=2.13.6=pyh6a1d191_3
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyside6=6.9.3=py311hf70c7b4_1
  - python=3.11.14=h0159041_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=8_cp311
  - pytorch=2.8.0=cuda128_mkl_py311_h889696f_302
  - pytz=2025.2=pyhd8ed1ab_0
  - pywavelets=1.9.0=py311h17033d2_1
  - pyyaml=6.0.3=py311h3f79411_0
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.9.3=ha0de62e_1
  - rav1e=0.7.1=ha073cba_3
  - rich=14.2.0=pyhcf101f3_0
  - scikit-image=0.25.2=py311h11fd7f3_2
  - scikit-learn=1.7.2=py311h8a15ebc_0
  - scipy=1.16.3=py311hf127856_1
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=h67fd636_0
  - slicerator=1.1.0=pyhd8ed1ab_1
  - snappy=1.2.2=h7fa0ca8_0
  - svt-av1=3.1.2=hac47afa_0
  - sympy=1.14.0=pyh04b8f61_5
  - tbb=2022.3.0=hd094cb3_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tifffile=2025.10.16=pyhd8ed1ab_0
  - tk=8.6.13=h2c6b04d_2
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.26100.0=h57928b3_0
  - unicodedata2=17.0.0=py311h3485c13_0
  - vc=14.3=h2b53caa_32
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - vs2015_runtime=14.44.35208=h38c0c73_32
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=1.17.3=py311h3485c13_1
  - xmltodict=1.0.2=pyhcf101f3_0
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - yaml=0.2.5=h6a83c73_3
  - zarr=3.1.3=pyhcf101f3_0
  - zfp=1.0.1=h2f0f97f_3
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib-ng=2.2.5=h32d8bfd_0
  - zstd=1.5.7=hbeecb71_2
prefix: C:\Users\klumpe\AppData\Local\miniconda3\envs\organoid_tracker
